# Generated by Django 6.1.1 on 2026-10-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_DB',
            fields=[
                ('Seriel_No', models.CharField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('DoB', models.DateField()),
                ('Address', models.TextField()),
                ('Mobile', models.IntegerField()),
                ('Vechicle', models.CharField()),
                ('Received_Date', models.DateField()),
            ],
        ),
    ]
